server:
  error:
    include-stacktrace: ON_PARAM

spring:
  application:
    name: springboot2-essencials
  datasource:
    url: jdbc:mysql://localhost:3308/tale_store?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: senha123
  jpa:
    hibernate:
      ddl-auto:

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG